const translations = {
    "ہوم": "Home",
    "ہمارا": "Our",
    "تعارف": "Introduction",
    "پولیس": "Police",
    "کریکٹر سرٹیفکیٹ": "Character Certificate",
    "جنرل پولیس ویریفیکیشن": "General Police Verification",
    "جرم کی رپورٹ": "Crime Report",
    "ڈپلیکیٹ ڈرائیونگ لائسنس": "Duplicate Driving License",
    "لرنر ڈرائیونگ لائسنس": "Learner Driving License",
    "گمشدگی رپورٹ": "Missing Report",
    "تجدید انٹرنیشنل ڈرائیونگ لائسنس": "Renewal Int. Driving License",
    "تجدید لرنر ڈرائیونگ لائسنس": "Renewal Learner Driving License",
    "تجدید ریگولر ڈرائیونگ لائسنس": "Renewal Regular Driving License",
    "سیف سٹی چالان": "Safe City Challan",
    "ٹریفک چالان": "Traffic Challan",
    "نادرہ": "NADRA",
    "بائیومیٹرک": "Biometric",
    "شناختی کارڈ": "Identity Card",
    "یوٹیلٹی بلز": "Utility Bills",
    "تعلیم": "Education",
    "علامہ اقبال اوپن یونیورسٹی": "Allama Iqbal Open University",
    "سرگودھا یونیورسٹی": "Sargodha University",
    "سرگودھا بورڈ": "Sargodha Board",
    "ٹریول سروسز": "Travel Services",
    "ہوائی ٹکٹ": "Air Tickets",
    "ریلوے ٹکٹ": "Railway Tickets",
    "ایکسائز اینڈ ٹیکسیشن": "Excise & Taxation",
    "وہیکل نیو رجسٹریشن": "New Vehicle Registration",
    "وہیکل ٹرانسفر": "Vehicle Transfer",
    "لوکل گورنمنٹ": "Local Government",
    "برتھ سرٹیفکیٹ": "Birth Certificate",
    "ڈیتھ سرٹیفکیٹ": "Death Certificate",
    "طلاق نامہ / ڈائیورس سرٹیفکیٹ": "Divorce Certificate",
    "نکاح نامہ / میرج سرٹیفکیٹ": "Marriage Certificate",
    "بورڈ آف ریونیو": "Board of Revenue",
    "ڈومیسائل سرٹیفکیٹ": "Domicile Certificate",
    "ڈپلیکیٹ ڈومیسائل": "Duplicate Domicile",
    "ای اسٹامپنگ": "E-Stamping",
    "انتقال کی کاپی": "Mutation Copy",
    "رجسٹری کی کاپی": "Registry Copy",
    "ڈومیسائل میں تبدیلی": "Domicile Modification",
    "ڈومیسائل این او سی": "Domicile NOC",
    "فرد": "Fard",
    "فرد برائے ذاتی ریکارڈ": "Fard for Personal Record",
    "فرد برائے بیع": "Fard for Sale",
    "فرد برائے حصول قرضہ": "Fard for Loan",
    "فرد برائے بجلی، گیس کنکشن و دیگر": "Fard for Electricity & Gas",
    "تازہ ترین": "Latest",
    "پنجاب لینڈ ریکارڈ اتھارٹی کی تمام سہولیات اب دستیاب ہیں۔": "Punjab Land Record Authority facilities are now available.",
    "علامہ اقبال اوپن یونیورسٹی کے داخلے شروع ہو چکے ہیں۔": "Allama Iqbal Open University admissions have started.",
    "مریم کی دستک سروسز کے ذریعے گھر بیٹھے سرٹیفکیٹس حاصل کریں۔": "Get certificates at home through Maryam Ki Dastak services.",
    "نادرہ ای-سہولت کے ذریعے یوٹیلٹی بلز کی ادائیگی پر کوئی اضافی فیس نہیں۔": "No extra charges on utility bill payments via NADRA e-Sahulat.",
    "ایکسائز اینڈ ٹیکسیشن کے نئے گاڑیوں کی رجسٹریشن اور ٹرانسفر کی سہولت موجود ہے۔": "Excise & Taxation new vehicle registration and transfer facility available.",
    "ڈومیسائل اور برتھ سرٹیفکیٹ بنوانے کے لیے آج ہی رابطہ کریں۔": "Contact today for Domicile and Birth Certificate.",
    "اندرون اور بیرون ملک سفر کے لیے ٹکٹنگ کی سہولت 'فواز ٹریول' کے اشتراک سے۔": "Ticketing facility for domestic and international travel with 'Fawaz Travel'.",
    "اعلیٰ معیار کی گرافک ڈیزائننگ سروسز آپ کے کاروبار کے لیے۔": "High-quality graphic designing services for your business.",
    "سرگودھا یونیورسٹی اور سرگودھا بورڈ کے امتحانات اور رزلٹس کی معلومات۔": "Information on Sargodha University and Sargodha Board exams and results.",
    "جلد آرہا ہے: ای-اسٹامپ (E-Stamp) وینڈر سروسز!": "Coming Soon: E-Stamp Vendor Services!",
    "تلاوت قرآن": "Quran Recitation",
    "رکیں (Pause)": "Pause",
    "مزید پڑھیں": "Read More",
    "ہماری": "Our",
    "خدمات": "Services",
    "ہماری خدمات دیکھیں": "View Our Services",
    "ہم سے رابطہ کریں": "Contact Us",
    "پنجاب لینڈ ریکارڈ اتھارٹی کی نئی آن لائن سہولیات کا آغاز": "Launch of New Online Facilities by Punjab Land Record Authority",
    "اب زمین کے تمام معاملات اور فرد کا حصول مزید آسان اور تیز ہو گیا ہے۔ ٹائم سیو سروسز کے ذریعے آپ گھر بیٹھے یہ تمام سہولیات حاصل کر سکتے ہیں...": "Now all land matters and getting Fard is easier and faster. Through Time Save Services, you can get these services from home...",
    "علامہ اقبال اوپن یونیورسٹی کے داخلے جاری": "Allama Iqbal Open University Admissions Open",
    "مریم کی دستک سے سرٹیفکیٹس کی ہوم ڈلیوری": "Home Delivery of Certificates via Maryam Ki Dastak",
    "نادرہ ای-سہولت پر بلوں کی ادائیگی": "Bill Payments on NADRA e-Sahulat",
    "گاڑیوں کی نئی رجسٹریشن کا طریقہ کار": "Procedure for New Vehicle Registration",
    "ٹریول سروسز اور ہوائی ٹکٹ کی بکنگ": "Travel Services and Air Ticket Booking",
    "کریکٹر سرٹیفکیٹ اور جنرل پولیس ویریفیکیشن کا حصول": "Acquiring Character Certificate and Gen. Police Verification",
    "اب تھانے جانے کی زحمت سے بچیں۔ جنرل پولیس ویریفیکیشن اور کریکٹر سرٹیفکیٹ کے حصول میں ہماری ٹائم سیو خدمات سے فائدہ اٹھائیں...": "Avoid the hassle of visiting the police station. Benefit from our services for Verification and Character Certificate...",
    "ای-اسٹامپنگ کی آن لائن سہولت": "Online Facility of E-Stamping",
    "ڈومیسائل اور برتھ سرٹیفکیٹ بنوائیں": "Get Domicile and Birth Certificates",
    "پروفیشنل گرافک ڈیزائننگ سروسز": "Professional Graphic Designing Services",
    "نادرہ شناختی کارڈ کی تجدید اب اور بھی آسان": "NADRA ID Card Renewal Now Easier",
    "فرد برائے حصول قرضہ کی فوری فراہمی": "Quick Delivery of Fard for Loan",
    "پاسپورٹ فیس کی ادائیگی بذریعہ ای-سہولت": "Passport Fee Payment via e-Sahulat",
    "لرنر ڈرائیونگ لائسنس گھر بیٹھے بنوائیں": "Get Learner Driving License from Home",
    "سرگودھا بورڈ میٹرک امتحانات کی فیس جمع کروائیں": "Submit Sargodha Board Matric Exam Fee",
    "بجلی اور گیس کے بلوں کی ادائیگی پر رعایت": "Discount on Electricity and Gas Bill Payments",
    "ڈیتھ سرٹیفکیٹ کا حصول اب مریم کی دستک سے": "Get Death Certificate Now via Maryam Ki Dastak",
    "موٹر سائیکل کی نئی رجسٹریشن فیس میں کمی": "Reduction in New Motorcycle Registration Fee",
    "عمرہ پیکج اور ٹکٹنگ کی بہترین سہولت": "Best Umrah Package and Ticketing Facility",
    "نکاح نامہ اور میرج سرٹیفکیٹ آن لائن": "Nikkah Nama and Marriage Certificate Online",
    "بین الاقوامی ڈرائیونگ لائسنس کی تجدید": "Renewal of International Driving License",
    "اراضی کا انتقال اور رجسٹری کی کاپی": "Land Mutation and Registry Copy",
    "ریلوے کی ای ٹکٹنگ سے سفر کو آسان بنائیں": "Make Travel Easy with Railway e-Ticketing",
    "صوبائی اور وفاقی محکموں کے چالان جمع کروائیں": "Submit Provincial and Federal Department Challans",
    "فرد برائے بیع (فروخت) کا آن لائن حصول": "Online Acquisition of Fard for Sale",
    "سرگودھا یونیورسٹی کا نیا امتحانی شیڈول جاری": "Sargodha University New Exam Schedule Released",
    "اپنے بزنس کے لیے خوبصورت لوگو ڈیزائن کروائیں": "Get Beautiful Logo Designs for Your Business",
    "ٹریفک چالان اور سیف سٹی ای چالان کی ادائیگی": "Payment of Traffic Challan and Safe City e-Challan",
    "نادرہ بائیومیٹرک تصدیق کی خدمات": "NADRA Biometric Verification Services",
    "Time Save Services – آپ کا وقت، ہماری ترجیح": "Time Save Services – Your Time, Our Priority",
    "جدید ڈیجیٹل سہولیات، سرکاری خدمات اور ٹریول سروسز کا بااعتماد مرکز": "A trusted center for modern digital facilities, government, and travel services",
    "ٹائم سیو سروسز (Time Save Services) جھاوریاں میں ایک ایسا ادارہ ہے جو عوام کی سہولت کو مدنظر رکھتے ہوئے قائم کیا گیا ہے۔ ہمارا مقصد ایک ہی چھت تلے تمام ضروری سرکاری اور ڈیجیٹل سہولیات فراہم کرنا ہے تاکہ آپ کو مختلف دفاتر کے چکر نہ لگانے پڑیں۔ ہم \"وقت کی بچت\" کے اصول پر کاربند ہیں اور اپنی خدمات کو تیز ترین، شفاف اور محفوظ بنانے کے لیے کوشاں ہیں۔": "Time Save Services is an organization established in Jhawarian keeping public convenience in mind. Our goal is to provide all essential government and digital facilities under one roof. We adhere to the principle of \"time saving\" and strive to make our services extremely fast, transparent, and secure.",
    "ہمارے پاس تجربہ کار عملہ موجود ہے جو آپ کے مسائل کو سمجھتا ہے اور انہیں پیشہ ورانہ مہارت کے ساتھ حل کرنے کی صلاحیت رکھتا ہے۔": "We have experienced staff who understand your problems and have the capability to solve them with professional expertise.",
    "ہم مندرجہ ذیل بے مثال سہولیات پیش کرتے ہیں": "We offer the following unparalleled facilities",
    "نادرہ ای-سہولت (NADRA e-Sahulat)": "NADRA e-Sahulat",
    "بجلی، گیس اور ٹیلی فون کے بلوں کی باآسانی ادائیگی اور شناختی کارڈ سے متعلقہ بنیادی رہنمائی۔": "Easy payment of electricity, gas, and telephone bills, and basic guidance related to Identity Cards.",
    "اراضی معاون (Arazi Muawin)": "Arazi Muawin (Land Assistant)",
    "پنجاب لینڈ ریکارڈ اتھارٹی کی تمام سہولیات، بشمول فرد کا حصول، انتقالِ اراضی اور زمین کے معاملات میں قانونی و تکنیکی مشاورت۔": "All Punjab Land Record Authority facilities, including getting Fard, land mutation, and legal/technical consultation.",
    "مریم کی دستک (Maryam Ki Dastak Facilitator)": "Maryam Ki Dastak Facilitator",
    "حکومتِ پنجاب کا انقلابی قدم! ہم بطور سہولت کار آپ کو ڈومیسائل، برتھ سرٹیفکیٹ، اور دیگر اہم سرکاری دستاویزات کی ہوم ڈلیوری سروس فراہم کرتے ہیں۔": "A revolutionary step by the Government! As facilitators, we provide home delivery service for essential government documents.",
    "گرافک ڈیزائننگ (Graphic Designing)": "Graphic Designing",
    "اپنے کاروبار یا ذاتی استعمال کے لیے اعلیٰ معیار کے پوسٹرز، بزنس کارڈز، لیٹر ہیڈز، لوگوز اور سوشل میڈیا اشتہارات ہم سے ڈیزائن کروائیں۔": "Get high-quality posters, business cards, letterheads, logos, and social media ads designed by us.",
    "ہمیں کیوں": "Why Choose",
    "منتخب کریں؟": "Us?",
    "وقت کی بچت": "Save Time",
    "تمام سہولیات ایک ہی جگہ پر۔": "All facilities in one place.",
    "بھروسہ مند": "Reliable",
    "شفاف لین دین اور درست کام۔": "Transparent transactions and accurate work.",
    "پیشہ ورانہ رویہ": "Professional Attitude",
    "ہنر مند عملہ اور بہترین کسٹمر سروس۔": "Skilled staff and excellent customer service.",
    "آسانی": "Convenience",
    "جدید ٹیکنالوجی کا استعمال تاکہ آپ کا کام جلد مکمل ہو۔": "Use of modern technology ensuring quick work completion.",
    "رابطہ کی": "Contact",
    "معلومات": "Information",
    "کسی بھی معلومات یا سروس کے لیے ہم سے رابطہ کریں۔": "Contact us for any information or service.",
    "فون نمبر": "Phone Number",
    "واٹس ایپ / فون نمبر": "WhatsApp / Phone Number",
    "واٹس ایپ پر رابطہ کریں:": "WhatsApp:",
    "ای میل": "Email",
    "پتہ": "Address",
    "کوٹ کمبوہ جھاوریاں، ضلع سرگودھا": "Kot Kamboh Jhawarian, District Sargodha",
    "براہِ کرم نیچے دیا گیا فارم پُر کریں، ہمارا نمائندہ جلد آپ سے رابطہ کرے گا": "Please fill out the form below; our representative will contact you soon.",
    "پورا نام (Full Name):": "Full Name:",
    "موبائل نمبر (Mobile Number):": "Mobile Number:",
    "ای میل ایڈریس (Email Address):": "Email Address:",
    "(اختیاری)": "(Optional)",
    "سروس منتخب کریں (Select Service):": "Select Service:",
    "سروس کا انتخاب کریں": "Choose a Service",
    "اراضی معاون / لینڈ ریکارڈ (Arazi Muawin / Land Record)": "Arazi Muawin / Land Record",
    "مریم کی دستک (Maryam Ki Dastak Services)": "Maryam Ki Dastak Services",
    "دیگر (Other)": "Other",
    "آپ کا پیغام (Your Message):": "Your Message:",
    "پیغام بھیجیں / Submit Message": "Submit Message",
    "© 2026 TIME SAVE SERVICES. تمام حقوق محفوظ ہیں۔": "© 2026 TIME SAVE SERVICES. All rights reserved.",
    "جلد آرہا ہے (Coming Soon)": "Coming Soon",
    "اپنا نام لکھیں": "Write your name",
    "یہاں اپنا پیغام لکھیں...": "Write your message here...",
    "25 فروری 2026": "25 February 2026",
    "24 فروری 2026": "24 February 2026",
    "22 فروری 2026": "22 February 2026",
    "20 فروری 2026": "20 February 2026",
    "18 فروری 2026": "18 February 2026",
    "15 فروری 2026": "15 February 2026",
    "12 فروری 2026": "12 February 2026",
    "10 فروری 2026": "10 February 2026",
    "08 فروری 2026": "08 February 2026",
    "05 فروری 2026": "05 February 2026",
    "04 فروری 2026": "04 February 2026",
    "03 فروری 2026": "03 February 2026",
    "02 فروری 2026": "02 February 2026",
    "01 فروری 2026": "01 February 2026",
    "30 جنوری 2026": "30 January 2026",
    "29 جنوری 2026": "29 January 2026",
    "28 جنوری 2026": "28 January 2026",
    "27 جنوری 2026": "27 January 2026",
    "26 جنوری 2026": "26 January 2026",
    "25 جنوری 2026": "25 January 2026",
    "24 جنوری 2026": "24 January 2026",
    "23 جنوری 2026": "23 January 2026",
    "22 جنوری 2026": "22 January 2026",
    "21 جنوری 2026": "21 January 2026",
    "20 جنوری 2026": "20 January 2026",
    "19 جنوری 2026": "19 January 2026",
    "18 جنوری 2026": "18 January 2026",
    "17 جنوری 2026": "17 January 2026",
    "16 جنوری 2026": "16 January 2026",
    "15 جنوری 2026": "15 January 2026",
    "ای-اسٹامپ (E-Stamp) وینڈر سروسز۔": "E-Stamp Vendor Services.",
    "ہم سے رابطہ کریں": "Contact Us",
    "کریکٹر سرٹیفکیٹ": "Character Certificate",
    "ضروری دستاویزات:": "Required Documents:",
    "شناختی کارڈ": "ID Card",
    "پاسپورٹ": "Passport",
    "تصویر": "Picture",
    "فیس کی تفصیل:": "Fee Details:",
    "سرکاری فیس: 1000 روپے": "Government Fee: Rs. 1000",
    "سروس چارجز: 950 روپے": "Service Charges: Rs. 950",
    "کل ادائیگی: 1950 روپے": "Total Payment: Rs. 1950",
    "رابطہ کریں": "Contact Us",
    "سرکاری فیس 500 روپے + سروس چارجز": "Government Fee Rs. 500 + Service Charges",
    "سرکاری فیس 1000 روپے + سروس چارجز": "Government Fee Rs. 1000 + Service Charges",
    "جنرل پولیس ویریفیکیشن کی ضرورت و افادیت (تفصیل پڑھیں)": "Necessity & Utility of General Police Verification (Read Details)",
    "جنرل پولیس ویریفیکیشن": "General Police Verification",
    "ایک اہم عمل ہے جس کے ذریعے پولیس کسی فرد کے موجودہ یا مستقل پتے، شناختی کوائف، اور کسی قسم کے مجرمانہ ریکارڈ کی عدم موجودگی کی تصدیق کرتی ہے۔": "is an important process through which the police verify an individual's current or permanent address, identity credentials, and the absence of any criminal record.",
    "کرایہ داری:": "Tenancy:",
    "مکان یا دکان کرائے پر لینے یا دینے کے لیے کرایہ دار کی تصدیق۔": "Verification of a tenant before renting a house or shop.",
    "ملازمت:": "Employment:",
    "نئے ملازمین (خصوصاً گھریلو ملازمین، ڈرائیور، یا سیکیورٹی گارڈز) کی خدمات حاصل کرنے سے پہلے ان کی تصدیق۔": "Verification of new employees (especially domestic staff, drivers, or security guards) before hiring.",
    "تحفظ اور اعتماد:": "Security & Trust:",
    "یہ عمل معاشرے میں تحفظ کا احساس پیدا کرتا ہے اور کسی بھی ناخوشگوار واقعے سے بچاؤ میں مدد دیتا ہے۔": "This process creates a sense of security in society and helps prevent any untoward incidents.",
    "خلاصہ:": "Summary:",
    "جنرل پولیس ویریفیکیشن آپ کے ارد گرد موجود افراد کی ساکھ کی تصدیق کر کے آپ کے جان و مال کے تحفظ کو یقینی بناتی ہے۔": "General Police Verification ensures the protection of your life and property by verifying the credibility of individuals around you.",
    "اس سروس کے حصول کے لیے ٹائم سیو سروسز سے رابطہ کریں اور اپنا وقت بچائیں۔": "Contact Time Save Services for this service and save your time.",
    "جرم کی رپورٹ": "Crime Report",
    "ضروری تفصیلات:": "Required Details:",
    "جرم کی رپورٹ درج کروانے کے لیے درج ذیل معلومات درکار ہوں گی:": "The following information will be required to file a crime report:",
    "شکایت کنندہ کا شناختی کارڈ": "Complainant's ID Card",
    "وقوعہ کی مکمل تفصیل": "Complete details of the incident",
    "جائے وقوعہ اور وقت": "Place and time of the incident",
    "صرف سروس چارجز (سرکاری فیس لاگو نہیں)": "Only Service Charges (No Government Fee applicable)",
    "رپورٹ درج کروانے کے لیے ٹائم سیو سروسز سے رابطہ کریں۔": "Contact Time Save Services to file the report.",
    "ڈپلیکیٹ ڈرائیونگ لائسنس": "Duplicate Driving License",
    "ضروری کاغذات اور معلومات:": "Required Documents & Information:",
    "ڈپلیکیٹ ڈرائیونگ لائسنس بنوانے کے لیے درج ذیل چیزیں درکار ہوں گی:": "The following items will be required to get a duplicate driving license:",
    "ایف آئی آر کی کاپی (FIR)": "Copy of FIR",
    "سرکاری فیس 680 روپے + سروس چارجز": "Government Fee Rs. 680 + Service Charges",
    "لرنر ڈرائیونگ لائسنس": "Learner Driving License",
    "لرنر ڈرائیونگ لائسنس بنوانے کے لیے درج ذیل چیزیں درکار ہوں گی:": "The following items will be required to get a learner driving license:",
    "میڈیکل سرٹیفکیٹ (50 سال سے زائد عمر کی صورت میں)": "Medical Certificate (in case of age over 50 years)",
    "گمشدگی کی رپورٹ": "Missing Report",
    "کسی بھی چیز (مثلاً شناختی کارڈ، موبائل، دستاویزات وغیرہ) کی گمشدگی کی رپورٹ کے لیے درج ذیل معلومات درکار ہوں گی:": "The following information will be required to report the loss of any item (e.g., ID card, mobile, documents, etc.):",
    "رپورٹ کنندہ کا شناختی کارڈ": "Reporter's ID Card",
    "گمشدہ چیز کی مکمل تفصیل": "Complete details of the missing item",
    "گمشدگی کا مقام اور وقت": "Place and time of loss",
    "تجدید انٹرنیشنل ڈرائیونگ لائسنس": "Renewal International Driving License",
    "انٹرنیشنل ڈرائیونگ لائسنس کی تجدید کے لیے درج ذیل چیزیں درکار ہوں گی:": "The following items will be required for the renewal of an international driving license:",
    "پاسپورٹ اور ویزا کی کاپی": "Copy of Passport and Visa",
    "پرانا انٹرنیشنل ڈرائیونگ لائسنس": "Old International Driving License",
    "سرکاری فیس (حسب ضابطہ) + سروس چارجز": "Government Fee (As per rules) + Service Charges",
    "تجدید لرنر ڈرائیونگ لائسنس": "Renewal Learner Driving License",
    "لرنر ڈرائیونگ لائسنس کی تجدید کے لیے درج ذیل چیزیں درکار ہوں گی:": "The following items will be required for the renewal of a learner driving license:",
    "پرانا لرنر لائسنس": "Old Learner License",
    "تجدید ریگولر ڈرائیونگ لائسنس": "Renewal Regular Driving License",
    "ریگولر ڈرائیونگ لائسنس کی تجدید کے لیے درج ذیل چیزیں درکار ہوں گی:": "The following items will be required for the renewal of a regular driving license:",
    "پرانا ڈرائیونگ لائسنس": "Old Driving License",
    "سرکاری فیس (مدت کے لحاظ سے) + سروس چارجز": "Government Fee (Depending on duration) + Service Charges",
    "علامہ اقبال اوپن یونیورسٹی (AIOU) نے سمسٹر بہار 2026 کے داخلوں کا آغاز کر دیا ہے۔ میٹرک، ایف اے، آئی کام، اور مختلف سرٹیفکیٹ کورسز میں داخلے جاری ہیں۔ داخلہ فارم جمع کروانے اور پراسپیکٹس حاصل کرنے کے لیے ٹائم سیو سروسز سے رابطہ کریں۔": "Allama Iqbal Open University (AIOU) has started Spring 2026 semester admissions. Admissions are open for Matric, FA, I.Com, and various certificate courses. Contact Time Save Services to submit the admission form and get the prospectus.",
    "ضروری کاغذات:": "Required Documents:",
    "سابقہ تعلیمی اسناد (پچھلی ڈگری / رزلٹ کارڈ)": "Previous Educational Documents (Previous Degree / Result Card)",
    "شناختی کارڈ یا ب فارم کی کاپی": "Copy of ID Card or B-Form",
    "ڈومیسائل کی کاپی": "Copy of Domicile",
    "والدین/سرپرست کا شناختی کارڈ": "Parent's/Guardian's ID Card",
    "پاسپورٹ سائز تصویر": "Passport Size Photograph",
    "نوٹ:": "Note:",
    "آن لائن داخلہ فارم فل کروانے اور فیس جمع کروانے کے لیے ہماری خدمات حاصل کریں۔": "Avail our services to fill the online admission form and submit the fee.",
    "سیف سٹی چالان": "Safe City Challan",
    "سیف سٹی چالان (E-Challan) کی ادائیگی اور تفصیلات کے لیے درج ذیل معلومات درکار ہوں گی:": "The following information will be required to pay and view details of a Safe City Challan (E-Challan):",
    "گاڑی کا نمبر (Registration Number)": "Vehicle Registration Number",
    "مالک کا شناختی کارڈ (اگر ضروری ہو)": "Owner's ID Card (if required)",
    "چالان کی رقم + سروس چارجز": "Challan Amount + Service Charges",
    "ٹریفک چالان": "Traffic Challan",
    "ٹریفک پولیس کے مینوئل یا ڈیجیٹل چالان کی ادائیگی کے لیے درج ذیل معلومات درکار ہوں گی:": "The following information will be required to pay a manual or digital traffic police challan:",
    "چالان کا پی ایس آئی ڈی (PSID) یا چالان نمبر": "Challan PSID or Challan Number",
    "تعلیمی ادارے": "Educational Institutions",
    "علامہ اقبال اوپن یونیورسٹی": "Allama Iqbal Open University",
    "علامہ اقبال اوپن یونیورسٹی کے داخلے": "Allama Iqbal Open University Admissions",
    "علامہ اقبال اوپن یونیورسٹی (AIOU) کے موجودہ داخلوں (میٹرک، ایف اے، آئی کام، اور سرٹیفکیٹ کورسز) کے لیے درج ذیل چیزیں درکار ہوں گی:": "The following items will be required for the current Allama Iqbal Open University (AIOU) admissions (Matric, FA, I.Com, and Certificate Courses):",
    "طالب علم کا شناختی کارڈ یا ب فارم کی کاپی": "Copy of Student's ID Card or B-Form",
    "پروگرام کی فیس (چالان کے مطابق) + سروس چارجز": "Program Fee (As per Challan) + Service Charges",
    "سرگودھا یونیورسٹی": "University of Sargodha",
    "اہم خدمات:": "Important Services:",
    "سرگودھا یونیورسٹی (University of Sargodha) سے متعلقہ درج ذیل آن لائن خدمات کے لیے ہم سے رابطہ کریں:": "Contact us for the following online services related to the University of Sargodha:",
    "نئے داخلوں کے لیے آن لائن اپلائی": "Online Apply for New Admissions",
    "امتحانات کے لیے آن لائن رجسٹریشن": "Online Registration for Exams",
    "ڈگری / ٹرانسکرپٹ کے حصول کے لیے اپلائی": "Apply for Degree / Transcript",
    "آن لائن فیس چالان جنریٹ کرنا": "Generate Online Fee Challan",
    "رزلٹ چیک کرنا": "Check Result",
    "یونیورسٹی فیس (چالان کے مطابق) + سروس چارجز": "University Fee (As per Challan) + Service Charges",
    "بورڈ آف انٹرمیڈیٹ اینڈ سیکنڈری ایجوکیشن سرگودھا": "Board of Intermediate and Secondary Education Sargodha",
    "میٹرک، ایف اے/ایف ایس سی اور دیگر بورڈ امتحانات سے متعلقہ درج ذیل خدمات کے لیے رابطہ کریں:": "Contact for the following services related to Matric, FA/FSC, and other board exams:",
    "داخلہ فارم فل کروانا (پرائیویٹ / ریگولر)": "Fill Admission Form (Private / Regular)",
    "رولنمبر سلپ ڈاؤن لوڈ کرنا": "Download Roll Number Slip",
    "رزلٹ کارڈ یا سند (Certificate) کے لیے اپلائی": "Apply for Result Card or Certificate",
    "پیپر ری چیکنگ کے لیے درخواست": "Application for Paper Rechecking",
    "نام / ولدیت یا تاریخ پیدائش میں تبدیلی کی درخواست": "Application for Change in Name / Father's Name or Date of Birth",
    "بورڈ فیس (چالان کے مطابق) + سروس چارجز": "Board Fee (As per Challan) + Service Charges",
    "برتھ سرٹیفکیٹ": "Birth Certificate",
    "ضروری تفصیلات اور کاغذات:": "Required Details and Documents:",
    "لوکل گورنمنٹ / یونین کونسل سے برتھ سرٹیفکیٹ کے حصول کے لیے درج ذیل معلومات اور کاغذات درکار ہوں گے:": "The following information and documents will be required to get a birth certificate from Local Government / Union Council:",
    "بچے کا نام اور تاریخ پیدائش": "Child's name and date of birth",
    "ہسپتال کا سرٹیفکیٹ یا ویکسینیشن کارڈ (اگر دستیاب ہو)": "Hospital certificate or vaccination card (if available)",
    "والدین (والد اور والدہ) کے شناختی کارڈز کی کاپیاں": "Copies of parents' (father and mother) ID cards",
    "درخواست دہندہ کے شناختی کارڈ کی کاپی": "Copy of applicant's ID card",
    "سرکاری فیس + سروس چارجز": "Government Fee + Service Charges",
    "ڈیتھ سرٹیفکیٹ": "Death Certificate",
    "لوکل گورنمنٹ / یونین کونسل سے ڈیتھ سرٹیفکیٹ کے حصول کے لیے درج ذیل معلومات اور کاغذات درکار ہوں گے:": "The following information and documents will be required to get a death certificate from Local Government / Union Council:",
    "متوفی (وفات پانے والے) کے شناختی کارڈ کی کاپی": "Copy of the deceased's ID card",
    "ہسپتال کا سرٹیفکیٹ یا قبرستان کی رسید (اگر ہو)": "Hospital certificate or graveyard receipt (if any)",
    "طلاق نامہ / ڈائیورس سرٹیفکیٹ": "Divorce Certificate",
    "لوکل گورنمنٹ / یونین کونسل سے طلاق نامہ (کمپیوٹرائزڈ) کے حصول کے لیے درج ذیل کاغذات درکار ہوں گے:": "The following documents will be required to get a (computerized) divorce certificate from Local Government / Union Council:",
    "طلاق کی تحریر یا عدالتی ڈگری کی کاپی": "Copy of divorce deed or court decree",
    "شوہر اور بیوی کے شناختی کارڈز کی کاپیاں": "Copies of husband and wife's ID cards",
    "نکاح نامہ / میرج سرٹیفکیٹ": "Marriage Certificate",
    "لوکل گورنمنٹ / یونین کونسل سے نکاح نامہ (کمپیوٹرائزڈ) کے حصول کے لیے درج ذیل معلومات درکار ہوں گی:": "The following information will be required to get a (computerized) marriage certificate from Local Government / Union Council:",
    "نکاح نامہ کی واضح کاپی": "Clear copy of Nikkah Nama",
    "دلہا، دلہن کے شناختی کارڈز کی کاپیاں": "Copies of bride and groom's ID cards",
    "دونوں کے والدین کے شناختی کارڈز کی کاپیاں (اگر ممکن ہو)": "Copies of both parents' ID cards (if possible)",
    "ڈومیسائل سرٹیفکیٹ": "Domicile Certificate",
    "تصویر متصدقہ": "Attested Photograph",
    "تعلیمی سند یا سکول سرٹیفکیٹ": "Educational Certificate or School Certificate",
    "ڈپلیکیٹ ڈومیسائل": "Duplicate Domicile",
    "پرانے ڈومیسائل کی کاپی یا گمشدگی کی رپورٹ": "Copy of Old Domicile or Missing Report",
    "تصویر": "Photograph",
    "ای اسٹامپنگ": "E-Stamping",
    "خریدار، فروخت کنندہ اور گواہان کے شناختی کارڈز کی کاپی": "Copies of ID Cards of Buyer, Seller, and Witnesses",
    "فرد برائے بیع کی کاپی": "Copy of Fard for Sale",
    "سرکاری مالیت کے مطابق + سروس چارجز": "According to Government Value + Service Charges",
    "انتقال کی کاپی": "Mutation Copy",
    "مالک کا شناختی کارڈ": "Owner's ID Card",
    "انتقال نمبر اور سال": "Mutation Number and Year",
    "رجسٹری کی کاپی": "Registry Copy",
    "رجسٹری نمبر، جلد اور سال": "Registry Number, Volume, and Year",
    "ڈومیسائل میں تبدیلی": "Domicile Modification",
    "اصل ڈومیسائل": "Original Domicile",
    "تبدیلی کا ثبوت (جیسے میرج سرٹیفکیٹ، نیا شناختی کارڈ وغیرہ)": "Proof of change (e.g., Marriage Certificate, New ID Card, etc.)",
    "ڈومیسائل این او سی": "Domicile NOC",
    "پرانے ضلع کا ڈومیسائل": "Domicile of Old District",
    "نئے ضلع کے پتے کا ثبوت": "Proof of Address of New District",
    "فرد برائے ذاتی ریکارڈ": "Fard for Personal Record",
    "مالک کا شناختی کارڈ (بائیو میٹرک تصدیق ضروری ہے)": "Owner's ID Card (Biometric verification required)",
    "فرد برائے بیع": "Fard for Sale",
    "فرد برائے حصول قرضہ": "Fard for Loan",
    "متعلقہ بینک کا لیٹر": "Relevant Bank Letter",
    "فرد برائے بجلی، گیس کنکشن و دیگر": "Fard for Electricity, Gas Connection & Others",
    "متعلقہ محکمے کی ضرورت کا ثبوت": "Proof of requirement from the relevant department",
    "ضروری تفصیلات اور معلومات:": "Required Details and Information:",
    "ریلوے ٹکٹ کی بکنگ کے لیے درج ذیل معلومات درکار ہوں گی:": "The following information will be required for booking a railway ticket:",
    "شناختی کارڈ / CNIC نمبر": "ID Card / CNIC Number",
    "موبائل نمبر": "Mobile Number",
    "تاریخ (سفر کب کرنا ہے)": "Date (When to travel)",
    "سفر کی تفصیل (کہاں سے کہاں تک جانا ہے)": "Travel Details (From where to where)",
    "ٹکٹ کی قیمت + سروس چارجز": "Ticket Price + Service Charges",
    "وہیکل نیو رجسٹریشن": "New Vehicle Registration",
    "نئی گاڑی (موٹر سائیکل/کار) کی رجسٹریشن کے لیے درج ذیل کاغذات درکار ہوں گے:": "The following documents will be required for the registration of a new vehicle (motorcycle/car):",
    "گاڑی کی انوائس (اصل)": "Vehicle Invoice (Original)",
    "سیلز لیٹر (اصل)": "Sales Letter (Original)",
    "مالک کا شناختی کارڈ (اصل)": "Owner's ID Card (Original)",
    "وہیکل ٹرانسفر": "Vehicle Transfer",
    "گاڑی (موٹر سائیکل/کار) کو اپنے نام ٹرانسفر کروانے کے لیے درج ذیل کاغذات کی ضرورت ہوگی:": "The following documents will be required to transfer the vehicle (motorcycle/car) to your name:",
    "خریدار اور فروخت کنندہ کی بائیو میٹرک تصدیق (Bio-Verification)": "Biometric Verification (Bio-Verification) of Buyer and Seller",
    "گاڑی کی رجسٹریشن بک یا سمارٹ کارڈ": "Vehicle Registration Book or Smart Card",
    "خریدار اور فروخت کنندہ کے شناختی کارڈ کی کاپیاں": "Copies of Buyer's and Seller's ID Cards",
    "دیگر": "Other",
    "سافٹ سکل": "Soft Skills",
    "پاکستان مرکنٹائل ایکسچینج": "Pakistan Mercantile Exchange",
    "پاکستان اسٹاک ایکسچینج": "Pakistan Stock Exchange",
    "پراپرٹی انویسٹمنٹ": "Property Investment",
    "سافٹ سکلز (Soft Skills)": "Soft Skills",
    "سافٹ سکلز کیا ہیں؟": "What are Soft Skills?",
    "سافٹ سکلز ان ذاتی خوبیوں اور صلاحیتوں کو کہا جاتا ہے جو آپ کو دوسروں کے ساتھ بہتر طریقے سے بات چیت کرنے، مل جل کر کام کرنے، اور مختلف حالات میں خود کو ڈھالنے میں مدد دیتی ہیں۔ ان میں مواصلات (Communication)، ٹیم ورک، وقت کی پابندی، اور مسائل کے حل کی صلاحیت شامل ہیں۔": "Soft skills are personal attributes and abilities that help you communicate effectively with others, work collaboratively, and adapt to different situations. These include communication, teamwork, time management, and problem-solving skills.",
    "یہ کس کے لیے ہیں؟": "Who is it for?",
    "طلباء جو پیشہ ورانہ زندگی کا آغاز کر رہے ہیں۔": "Students who are starting their professional life.",
    "پیشہ ور افراد جو اپنی کارکردگی اور ترقی کو بہتر بنانا چاہتے ہیں۔": "Professionals who want to improve their performance and career growth.",
    "کوئی بھی شخص جو اپنی انفرادی اور سماجی صلاحیتوں کو نکھارنا چاہتا ہو۔": "Anyone who wants to enhance their interpersonal and social skills.",
    "بیرون ملک سفر کے لیے لازمی:": "Mandatory for International Travel:",
    "سافٹ سکلز کا کورس اب بین الاقوامی سطح پر بیرون ملک جانے والوں کے لیے انتہائی اہمیت اختیار کر گیا ہے۔ کچھ ممالک نے اسے ورک ویزا اور دیگر مقاصد کے لیے لازمی قرار دے دیا ہے۔ یاد رکھیں، اس سرٹیفکیٹ کے بغیر پروٹیکٹر (Protector) نہیں لگتا، اس لیے بیرون ملک روزگار کے خواہش مند افراد کے لیے یہ کورس کرنا ناگزیر ہے۔": "Soft skills courses have become extremely important internationally for those traveling abroad. Some countries have made it mandatory for work visas and other purposes. Remember, without this certificate, a Protector cannot be obtained, making this course essential for those seeking employment overseas.",
    "ضروری چیزیں:": "Requirements:",
    "سیکھنے کا شوق اور مثبت رویہ।": "A desire to learn and a positive attitude.",
    "وقت دینے کی عزم۔": "Commitment of time.",
    "آن لائن کورسز کے لیے انٹرنیٹ اور ڈیوائس (اگر لاگو ہو)۔": "Internet and device for online courses (if applicable).",
    "کورسز کی تفصیل کے لیے واٹس ایپ پر رابطہ کریں: 03046994699": "Contact on WhatsApp for course details: 03046994699",
    "رابطہ": "Contact",
    "تمام ضروری سرکاری اور ڈیجیٹل سہولیات کا بااعتماد مرکز": "A trusted center for all essential government and digital facilities",
    "ری پرنٹ": "Reprint",
    "تجدید": "Renewal",
    "شناختی کارڈ کی خدمات (ری پرنٹ اور تجدید)": "ID Card Services (Reprint & Renewal)",
    "اب ٹائم سیو سروسز پر نادرہ شناختی کارڈ کی تجدید اور گم شدہ کارڈ کے ری پرنٹ کی سہولت بھی دستیاب ہے۔ دفتر کے چکروں سے بچیں اور اپنا کام باآسانی مکمل کروائیں۔": "Renewal of NADRA ID cards and reprint facility for lost cards is now available at Time Save Services. Avoid visits to the office and get your work done easily.",
    "ضروری کاغذات اور معلومات:": "Required Documents & Information:",
    "ری پرنٹ: پرانا شناختی کارڈ یا اس کی کاپی درکار ہے۔": "Reprint: Old ID card or its copy is required.",
    "تجدید: زائد المیعاد (Expired) شناختی کارڈ درکار ہے۔": "Renewal: Expired ID card is required.",
    "فیس: سرکاری فیس + سروس چارجز لاگو ہوں گے۔": "Fee: Government fee + service charges will apply.",
    "مزید معلومات اور فیس کی تفصیلات کے لیے ہمارے واٹس ایپ نمبر پر رابطہ کریں یا دفتر تشریف لائیں۔": "For more information and fee details, contact our WhatsApp number or visit the office.",
    "شناختی کارڈ کی خدمات": "ID Card Services",
    "ہماری خدمات:": "Our Services:",
    "شناختی کارڈ کی تجدید (Renewal) اور گمشدہ کارڈ کے ری پرنٹ (Reprint) کی سہولت موجود ہے۔": "Facility for Renewal and Reprint of lost ID card is available.",
    "ری پرنٹ (Reprint)": "Reprint",
    "تجدید (Renewal)": "Renewal",
    "پرانا شناختی کارڈ یا اس کی کاپی درکار ہے۔": "Old ID card or its copy is required.",
    "سرکاری فیس + مناسب سروس چارجز (Service Charges) لاگو ہوں گے۔": "Government Fee + appropriate Service Charges will apply.",
    "زائد المیعاد (Expired) شناختی کارڈ درکار ہے۔": "Expired ID card is required.",
    "مزید معلومات، سروس چارجز کی تفصیلات اور کام کے لیے ہمارے درج ذیل واٹس ایپ نمبر پر رابطہ کریں یا ہمارے دفتر تشریف لائیں۔": "For more information, details of service charges and work, contact our WhatsApp number below or visit our office.",
    "یوٹیلٹی بلز کی ادائیگی": "Utility Bills Payment",
    "نادرہ ای-سہولت کے ذریعے تمام یوٹیلٹی بلز کی ادائیگی کی سہولت بلاتفریق اور بغیر کسی اضافی چارجز کے دستیاب ہے۔": "Facility to pay all utility bills via NADRA e-Sahulat is available without any extra charges.",
    "بجلی کے بل (Electricity Bills)": "Electricity Bills",
    "فیسکو (FESCO)، واپڈا اور دیگر تمام کمپنیوں کے بل۔": "FESCO, WAPDA, and all other companies' bills.",
    "سوئی گیس (Sui Gas Bills)": "Sui Gas Bills",
    "سوئی ناردرن (SNGPL) اور سوئی سدرن گیس کے بل۔": "Sui Northern (SNGPL) and Sui Southern Gas bills.",
    "پی ٹی سی ایل اور انٹرنیٹ (PTCL & Internet)": "PTCL & Internet",
    "پی ٹی سی ایل لینڈ لائن، براڈ بینڈ، اور وائی فائی ڈیوائسز کے بل۔": "PTCL Landline, Broadband, and Wi-Fi devices bills.",
    "پانی اور دیگر (Water & Others)": "Water & Others",
    "واسا (WASA) کے بلوں کی ادائیگی۔": "Payment of WASA bills.",
    "مزید معلومات اور آن لائن بل جمع کروانے کے لیے ہمارے درج ذیل واٹس ایپ نمبر پر رابطہ کریں یا ہمارے دفتر تشریف لائیں۔": "For more information and online bill payment, contact our WhatsApp number below or visit our office.",
    "نادرہ بائیومیٹرک تصدیق": "NADRA Biometric Verification",
    "نادرہ ای-سہولت کے ذریعے مختلف محکموں اور مقاصد کے لیے بائیومیٹرک (فنگر پرنٹس) کی جدید ترین اور محفوظ ترین سہولت دستیاب ہے۔": "The latest and most secure biometric (fingerprints) facility is available for various departments and purposes through NADRA e-Sahulat.",
    "گاڑیوں کی خرید و فروخت (Vehicle Transfer)": "Vehicle Transfer",
    "ایکسائز اینڈ ٹیکسیشن کے لیے خریدار اور فروخت کنندہ کی بائیومیٹرک تصدیق۔": "Biometric verification of buyer and seller for Excise and Taxation.",
    "بینظیر انکم سپورٹ (BISP)": "Benazir Income Support (BISP)",
    "BISP اور دیگر فلاحی پروگرامز کی رقوم وصول کرنے کے لیے تصدیق۔": "Verification for receiving funds from BISP and other welfare programs.",
    "ذاتی و خاندانی تصدیق (Personal Verification)": "Personal Verification",
    "فیملی رجسٹریشن سرٹیفکیٹ (FRC)، وراثت، اور پنشن وغیرہ کے مقاصد کے لیے۔": "For Family Registration Certificate (FRC), inheritance, pension, and other purposes.",
    "چہرے کی شناخت (Facial Recognition)": "Facial Recognition",
    "مزید معلومات اور سروس چارجز کی تفصیلات کے لیے ہمارے درج ذیل واٹس ایپ نمبر پر رابطہ کریں یا ہمارے دفتر تشریف لائیں۔": "For more information and details of service charges, contact our WhatsApp number below or visit our office.",
    "اہم اطلاع: علامہ اقبال اوپن یونیورسٹی ڈیٹ شیٹ": "Important Notice: Allama Iqbal Open University Datesheet",
    "علامہ اقبال اوپن یونیورسٹی (AIOU) کی نئی ڈیٹ شیٹ جاری کر دی گئی ہے۔": "The new datesheet for Allama Iqbal Open University (AIOU) has been released.",
    "اپنی ڈیٹ شیٹ ڈاؤن لوڈ کریں۔": "Download your datesheet.",
    "امتحانات کی تاریخیں چیک کریں۔": "Check examination dates.",
    "پرنٹ آؤٹ کی سہولت مرکز پر دستیاب ہے۔": "Printout facility is available at the center.",
    "مزید معلومات کے لیے رابطہ کریں": "Contact for more information",
    "انکم ٹیکس رجسٹریشن": "Income Tax Registration",
    "انکم ٹیکس ریٹرن فائل": "Income Tax Return File",
    "نئے انکم ٹیکس دہندگان کے لیے ایف بی آر (FBR) میں رجسٹریشن اور این ٹی این (NTN) کے حصول کی مکمل سہولت فراہم کی جاتی ہے۔": "Complete facility is provided for registration and obtaining NTN in FBR for new income taxpayers.",
    "درکار دستاویزات": "Required Documents",
    "شناختی کارڈ کی کاپی": "Copy of ID Card",
    "آپ کے نام پر رجسٹرڈ موبائل نمبر": "Mobile number registered in your name",
    "ای میل ایڈریس": "Email Address",
    "گھر یا دفتر کے پتے کی تفصیل (بجلی کا بل)": "Home or office address details (Electricity bill)",
    "مزید معلومات اور رجسٹریشن کے لیے ہمارے درج ذیل واٹس ایپ نمبر پر رابطہ کریں یا ہمارے دفتر تشریف لائیں۔": "For more information and registration, contact our WhatsApp number below or visit our office.",
    "سالانہ انکم ٹیکس ریٹرن (Income Tax Return) کی تیاری اور ایف بی آر (FBR) میں جمع کروانے کی مکمل اور بروقت سہولت۔": "Complete and timely facility for preparing and submitting the annual Income Tax Return in FBR.",
    "اہم فوائد اور دستاویزات": "Important Benefits and Documents",
    "فائلر بنیں:": "Become a Filer:",
    "ریٹرن فائل کر کے فائلر بنیں اور ودہولڈنگ ٹیکسز (Withholding Taxes) کی بچت کریں۔": "File return to become a Filer and save on Withholding Taxes.",
    "درکار معلومات:": "Required Information:",
    "بینک اسٹیٹمنٹ، تنخواہ کی سلپ (اگر ملازم ہیں)، یا کاروبار کی آمدنی کی تفصیلات۔": "Bank statement, salary slip (if employed), or details of business income.",
    "یوٹیلٹی بلز:": "Utility Bills:",
    "سالانہ بجلی، گیس اور دیگر بلوں کی تفصیلات۔": "Details of annual electricity, gas, and other bills.",
    "بروقت ریٹرن فائل کرنے اور جرمانے سے بچنے کے لیے ہمارے درج ذیل واٹس ایپ نمبر پر رابطہ کریں یا ہمارے دفتر تشریف لائیں۔": "To file return on time and avoid penalty, contact our WhatsApp number below or visit our office.",
    "حکومتِ پنجاب کا ایک انقلابی قدم 'مریم کی دستک' اب ٹائم سیو سروسز پر دستیاب ہے۔ اب آپ کو سرکاری دفاتر کے چکر کاٹنے کی ضرورت نہیں، گھر بیٹھے مختلف سرٹیفکیٹس اور دستاویزات حاصل کریں۔": "A revolutionary step by the Government of Punjab 'Maryam Ki Dastak' is now available at Time Save Services. No need to visit government offices; get various certificates and documents sitting at home.",
    "ہماری فراہم کردہ ہوم ڈلیوری خدمات:": "Our provided home delivery services:",
    "برتھ سرٹیفکیٹ:": "Birth Certificate:",
    "نئے پیدا ہونے والے بچوں کا اندراج اور سرٹیفکیٹ کا حصول۔": "Registration of new borns and obtaining certificate.",
    "ڈیتھ سرٹیفکیٹ:": "Death Certificate:",
    "وفات پانے والے افراد کے ڈیتھ سرٹیفکیٹ کا اجراء۔": "Issuance of death certificate for deceased persons.",
    "میرج اور ڈائیورس سرٹیفکیٹ:": "Marriage & Divorce Certificate:",
    "نکاح نامہ اور طلاق نامہ کی کمپیوٹرائزڈ کاپی۔": "Computerized copy of Nikkah Nama and Divorce Certificate.",
    "طریقہ کار:": "Procedure:",
    "آپ صرف ہمیں مطلوبہ دستاویزات فراہم کریں، ہمارا نمائندہ تمام کارروائی مکمل کر کے سرٹیفکیٹ آپ کے گھر تک پہنچائے گا۔ سروس سے فائدہ اٹھانے کے لیے واٹس ایپ پر رابطہ کریں۔": "You just provide us the required documents; our representative will complete all the processing and deliver the certificate to your home. Contact us on WhatsApp to avail the service.",
    "نادرہ ای-سہولت کے ذریعے تمام یوٹیلٹی بلز کی ادائیگی کی سہولت بلاتفریق اور بغیر کسی اضافی چارجز کے دستیاب ہے۔ لائنوں میں لگنے کی زحمت سے بچیں اور فوری ادائیگی کریں۔": "Facility to pay all utility bills via NADRA e-Sahulat is available indiscriminately and without any extra charges. Avoid the hassle of standing in lines and pay instantly.",
    "ہماری فراہم کردہ سہولیات:": "Our Provided Facilities:",
    "بجلی کے بل:": "Electricity Bills:",
    "فیسکو (FESCO)، گیپکو (GEPCO)، لیسکو (LESCO) اور دیگر تمام بجلی کے بلوں کی ادائیگی۔": "Payment of FESCO, GEPCO, LESCO and all other electricity bills.",
    "گیس کے بل:": "Gas Bills:",
    "سوئی ناردرن (SNGPL) اور سوئی سدرن (SSGC) کے بلوں کی ادائیگی۔": "Payment of Sui Northern (SNGPL) and Sui Southern (SSGC) bills.",
    "پانی اور دیگر:": "Water and others:",
    "واسا (WASA) اور دیگر متعلقہ اداروں کے بل۔": "Bills of WASA and other relevant departments.",
    "ٹیلی فون اور انٹرنیٹ:": "Telephone and Internet:",
    "پی ٹی سی ایل (PTCL) لینڈ لائن، براڈ بینڈ اور فیملی پیکجز کی ادائیگی۔": "Payment of PTCL Landline, Broadband and Family packages.",
    "آپ اپنا بل ہمارے دفتر لا سکتے ہیں یا واٹس ایپ پر بل کی تصویر بھیج کر آن لائن پیمنٹ کے ذریعے گھر بیٹھے اپنا بل ادا کر سکتے ہیں۔": "You can bring your bill to our office or send a picture of the bill on WhatsApp to pay your bill from home via online payment.",
    "اب ایکسائز اینڈ ٹیکسیشن دفتر کے چکر لگانے کی ضرورت نہیں۔ ٹائم سیو سروسز کے ذریعے اپنی نئی موٹر سائیکل یا گاڑی کی رجسٹریشن کا عمل باآسانی مکمل کریں۔": "No need to visit Excise and Taxation office anymore. Easily complete the registration process of your new motorcycle or car through Time Save Services.",
    "ضروری کاغذات:": "Required Documents:",
    "گاڑی کی انوائس:": "Vehicle Invoice:",
    "شو روم کی طرف سے جاری کردہ اصل انوائس۔": "Original invoice issued by the showroom.",
    "سیلز لیٹر:": "Sales Letter:",
    "کمپنی کا جاری کردہ سیلز لیٹر (اصل)۔": "Original sales letter issued by the company.",
    "شناختی کارڈ:": "ID Card:",
    "مالک کے شناختی کارڈ کی اصل کاپی اور بائیو میٹرک تصدیق۔": "Original copy of owner's ID card and biometric verification.",
    "ہماری سروسز:": "Our Services:",
    "آن لائن فیس چالان جنریٹ کرنا۔": "Generate online fee challan.",
    "ای-پے (e-Pay) کے ذریعے فیس کی فوری ادائیگی۔": "Instant payment of fee through e-Pay.",
    "بائیو میٹرک تصدیق کی سہولت۔": "Facility of biometric verification.",
    "سمارٹ کارڈ اور نمبر پلیٹس کے لیے اپلائی کرنا۔": "Apply for smart card and number plates.",
    "آپ اصل کاغذات کے ساتھ ہمارے دفتر تشریف لائیں یا واٹس ایپ پر تفصیلات بھیج کر رہنمائی حاصل کریں۔ ہم رجسٹریشن کا عمل شفاف اور جلد مکمل کروائیں گے۔": "Visit our office with original documents or send details on WhatsApp for guidance. We will complete the registration process transparently and quickly.",
    "ٹائم سیو سروسز نے 'فواز ٹریول' (Fawaz Travel) کے اشتراک سے اندرون اور بیرون ملک سفر کے لیے بہترین اور سستی ٹکٹنگ کی سہولت متعارف کروائی ہے۔": "Time Save Services in collaboration with 'Fawaz Travel' has introduced the best and affordable ticketing facility for domestic and international travel.",
    "ہوائی ٹکٹ (Air Tickets):": "Air Tickets:",
    "دنیا بھر کی ایئر لائنز کے لیے سستے اور کنفرمڈ ہوائی ٹکٹ۔": "Cheap and confirmed air tickets for airlines worldwide.",
    "عمرہ پیکجز (Umrah Packages):": "Umrah Packages:",
    "آپ کے بجٹ کے مطابق بہترین عمرہ پیکجز اور ویزہ سروسز۔": "Best Umrah packages and visa services according to your budget.",
    "وزٹ ویزہ (Visit Visa):": "Visit Visa:",
    "دبئی، سعودی عرب اور دیگر ممالک کے لیے وزٹ ویزہ کی پروسیسنگ۔": "Processing of visit visas for Dubai, Saudi Arabia, and other countries.",
    "ٹریول انشورنس:": "Travel Insurance:",
    "دورانِ سفر کسی بھی غیر یقینی صورتحال سے بچاؤ کے لیے محفوظ انشورنس۔": "Secure insurance to protect against any unforeseen situation during travel.",
    "اپنی سفری ضروریات اور منزل کی تفصیلات بتانے کے لیے ہمارے واٹس ایپ نمبر پر رابطہ کریں، ہم آپ کو بہترین آپشنز فراہم کریں گے۔": "Contact our WhatsApp number to tell us your travel requirements and destination details, we will provide you with the best options.",
    "اب آپ کو پولیس اسٹیشن یا خدمت مرکز کے چکر لگانے کی کوئی ضرورت نہیں۔ ٹائم سیو سروسز کے ذریعے اپنا کریکٹر سرٹیفکیٹ اور جنرل پولیس ویریفیکیشن کا عمل گھر بیٹھے باآسانی مکمل کریں۔": "You no longer need to visit the police station or Khidmat Markaz. Easily complete the process of your Character Certificate and General Police Verification from home through Time Save Services.",
    "کریکٹر سرٹیفکیٹ (Character Certificate):": "Character Certificate:",
    "بیرون ملک سفر:": "International Travel:",
    "ویزہ کے حصول کے لیے لازمی دستاویز۔": "Mandatory document for obtaining a visa.",
    "ملازمت کا حصول:": "Obtaining Employment:",
    "سرکاری یا نجی نوکری کے لیے کردار کی درستگی کا ثبوت۔": "Proof of character accuracy for government or private jobs.",
    "اصل پاسپورٹ، شناختی کارڈ کی کاپی، اور تصویر درکار ہے۔": "Original passport, copy of ID card, and a photograph are required.",
    "جنرل پولیس ویریفیکیشن (General Police Verification):": "General Police Verification:",
    "مکان یا دکان کرائے پر دینے یا لینے کے لیے لازمی تصدیق۔": "Mandatory verification for renting out or taking on rent a house or shop.",
    "ملازمین کی تصدیق:": "Employees Verification:",
    "گھریلو ملازمین، ڈرائیورز یا سیکیورٹی گارڈز کی تصدیق۔": "Verification of domestic workers, drivers, or security guards.",
    "مقصد:": "Purpose:",
    "کرائم ریکارڈ کی عدم موجودگی کی تصدیق کے ذریعے تحفظ کو یقینی بنانا۔": "Ensuring security through confirmation of the absence of a criminal record.",
    "سہولت:": "Facility:",
    "ہماری سروس کے ذریعے تمام عمل آن لائن ہو گا اور آپ کو تھانے یا ڈی پی او آفس جانے کی ضرورت نہیں پڑے گی۔ تفصیلات کے لیے ہمارے واٹس ایپ نمبر پر رابطہ کریں۔": "Through our service, the entire process will be online, and you won't need to visit the police station or DPO office. Contact our WhatsApp number for details.",
    "ٹائم سیو سروسز کے ذریعے بچوں کے برتھ سرٹیفکیٹ اور ڈومیسائل بنوانے کی سہولت اب نہایت آسان اور تیز تر ہو گئی ہے۔ دفتروں کے چکر سے بچیں اور سہولت سے فائدہ اٹھائیں۔": "Through Time Save Services, the facility to obtain birth certificates and domiciles for children has now become very easy and fast. Avoid visiting offices and take advantage of the facility.",
    "برتھ سرٹیفکیٹ (Birth Certificate):": "Birth Certificate:",
    "نئے پیدا ہونے والے بچوں کا اندراج۔": "Registration of newborns.",
    "یونین کونسل سے کمپیوٹرائزڈ برتھ سرٹیفکیٹ کا حصول۔": "Obtaining computerized birth certificate from the Union Council.",
    "درکار کاغذات:": "Required Documents:",
    "ہسپتال کا سرٹیفکیٹ، والدین کے شناختی کارڈ کی کاپی۔": "Hospital certificate, copy of parents' ID cards.",
    "ڈومیسائل (Domicile):": "Domicile:",
    "نئے ڈومیسائل کے حصول کے لیے مکمل رہنمائی اور پراسیسنگ۔": "Complete guidance and processing for obtaining a new domicile.",
    "ضروری کاغذات:": "Required Documents:",
    "تصدیق شدہ تصاویر، فارم ب/شناختی کارڈ، والد کا شناختی کارڈ، اور رہائش کا ثبوت۔": "Attested photographs, Form-B/ID card, father's ID card, and proof of residence.",
    "مزید معلومات اور گھر بیٹھے سروس حاصل کرنے کے لیے ہمارے واٹس ایپ نمبر پر متعلقہ دستاویزات بھیجیں یا دفتر تشریف لائیں۔": "For more information and to get the service from home, send the relevant documents to our WhatsApp number or visit our office.",
    "ٹائم سیو سروسز کی جانب سے اب ہر قسم کی پروفیشنل گرافک ڈیزائننگ اور پرنٹنگ کی سہولیات بھی فراہم کی جا رہی ہیں۔ اپنے کاروبار کو ایک نئی پہچان دیں!": "Time Save Services is now providing all types of professional graphic designing and printing facilities. Give your business a new identity!",
    "شادی کارڈز (Wedding Cards):": "Wedding Cards:",
    "ہر قسم کے جدید اور خوبصورت شادی کارڈز کی ڈیزائننگ اور پرنٹنگ۔": "Designing and printing of all types of modern and beautiful wedding cards.",
    "پرنٹنگ (Printing):": "Printing:",
    "وزٹنگ کارڈز، لیٹر ہیڈ، بل بکس اور دیگر دفتری سٹیشنری کی معیاری پرنٹنگ۔": "Quality printing of visiting cards, letterheads, bill books, and other office stationery.",
    "پینافلکس (Panaflex):": "Panaflex:",
    "دکانوں، دفاتر اور اشتہارات کے لیے پینافلکس کی اعلیٰ کوالٹی ڈیزائننگ اور پرنٹنگ۔": "High-quality designing and printing of panaflex for shops, offices, and advertisements.",
    "سوشل میڈیا پوسٹس (Social Media Posts):": "Social Media Posts:",
    "فیس بک، انسٹاگرام اور دیگر پلیٹ فارمز کے لیے پرکشش پوسٹس کی ڈیزائننگ۔": "Designing attractive posts for Facebook, Instagram, and other platforms.",
    "اپنی ڈیزائننگ اور پرنٹنگ کی ضروریات کے لیے ہمارے دفتر تشریف لائیں یا واٹس ایپ کے ذریعے آن لائن آرڈر بک کروائیں۔": "Visit our office for your designing and printing needs or book an online order via WhatsApp.",
    "قطار اور انتظار کی زحمت سے بچیں! نادرہ شناختی کارڈ کی تجدید یا ری پرنٹ کے لیے ٹائم سیو سروسز سے رابطہ کریں اور اپنا ضروری کام بروقت مکمل کریں۔": "Avoid the hassle of queues and waiting! Contact Time Save Services for Nadra ID card renewal or reprint and get your essential work done on time.",
    "تجدید (Renewal):": "Renewal:",
    "زائد المیعاد (Expired) شناختی کارڈ کی باآسانی تجدید۔": "Easy renewal of expired ID card.",
    "ری پرنٹ (Reprint):": "Reprint:",
    "گمشدہ یا خراب کارڈ کی صورت میں نیا کارڈ حاصل کریں۔": "Get a new card in case of lost or damaged card.",
    "بائیو میٹرک تصدیق:": "Biometric Verification:",
    "شناختی کارڈ کے حصول کے لیے آن لائن بائیو میٹرک تصدیق کی سہولت بھی موجود ہے۔": "Online biometric verification facility is also available for obtaining the ID card.",
    "تفصیلات کے لیے ہمارے دفتر تشریف لائیں یا واٹس ایپ کے ذریعے رہنمائی حاصل کریں۔": "For details, visit our office or get guidance via WhatsApp.",
    "اب قرضہ حاصل کرنے کے لیے فرد کی ضرورت ہو تو اراضی ریکارڈ سینٹر / تحصیل کے چکر لگانے اور لمبی قطاروں میں انتظار کی زحمت سے بچیں۔": "Now, if you need a Fard (property document) to get a loan, avoid the hassle of visiting the Arazi Record Center / Tehsil and waiting in long queues.",
    "فوری حصول:": "Quick Attainment:",
    "ٹائم سیو سروسز کے ذریعے فرد برائے حصول قرضہ فوری طور پر حاصل کریں۔": "Get the Fard for loan immediately through Time Save Services.",
    "وقت کی بچت:": "Time Saving:",
    "اپنا قیمتی وقت بچائیں اور اپنا ضروری کام بروقت مکمل کریں۔": "Save your precious time and complete your essential work on time.",
    "تفصیلات جاننے اور سروس حاصل کرنے کے لیے ہمارے واٹس ایپ نمبر پر رابطہ کریں یا دفتر تشریف لائیں۔": "To know the details and get the service, contact our WhatsApp number or visit our office.",
    "اب پاسپورٹ فیس کی ادائیگی کے لیے بینکوں کی لمبی قطاروں میں لگنے کی ضرورت نہیں۔ ٹائم سیو سروسز کے پلیٹ فارم پر نادرہ ای-سہولت کے ذریعے اپنی فیس باآسانی ادا کریں۔": "Now there is no need to wait in long queues at banks to pay the passport fee. Easily pay your fee through Nadra e-Sahulat on the Time Save Services platform.",
    "خصوصیات:": "Features:",
    "فوری ادائیگی:": "Instant Payment:",
    "ای-سہولت کے ذریعے پاسپورٹ فیس کی فوری اور محفوظ ادائیگی۔": "Instant and secure payment of passport fee through e-Sahulat.",
    "ہر قسم کا پاسپورٹ:": "All Types of Passports:",
    "نیا پاسپورٹ، تجدید، ارجنٹ یا نارمل فیس کی سہولت۔": "Facility for new passport, renewal, urgent or normal fee.",
    "رسید کی فراہمی:": "Provision of Receipt:",
    "ادائیگی کے فوراً بعد تصدیقی رسید حاصل کریں۔": "Get a confirmation receipt immediately after payment.",
    "اپنا PSID نمبر یا متعلقہ تفصیلات لے کر ہمارے دفتر تشریف لائیں یا واٹس ایپ کے ذریعے رابطہ کریں۔": "Visit our office with your PSID number or relevant details, or contact us via WhatsApp.",
    "پاسپورٹ فیس کی تفصیل (Passport Fees):": "Passport Fee Details:",
    "صفحات": "Pages",
    "میعاد": "Validity",
    "نارمل": "Normal",
    "ارجنٹ": "Urgent",
    "فاسٹ ٹریک": "Fast Track",
    "5 سال": "5 Years",
    "10 سال": "10 Years",
    "* فیس میں حکومتی ٹیکس یا سروس چارجز شامل ہو سکتے ہیں۔": "* Fees may include government taxes or service charges.",
    "اب ٹریفک پولیس آفس کے چکر لگانے کی ضرورت نہیں۔ ٹائم سیو سروسز کے ذریعے اپنا لرنر ڈرائیونگ لائسنس گھر بیٹھے باآسانی بنوائیں۔": "No need to visit the Traffic Police Office anymore. Easily get your Learner Driving License from home through Time Save Services.",
    "ضروری معلومات:": "Essential Information:",
    "درکار کاغذات:": "Required Documents:",
    "شناختی کارڈ کی کاپی اور ایک تصویر درکار ہے۔": "A copy of ID card and one photograph are required.",
    "فیس کی تفصیل:": "Fee Details:",
    "فی کیٹیگری 500 روپے سرکاری فیس۔": "500 Rs official fee per category.",
    "یہ سہولت گھر بیٹھے حاصل کرنے کے لیے ہمارے واٹس ایپ نمبر پر اپنے کاغذات بھیجیں یا دفتر تشریف لائیں۔": "To get this facility at home, send your documents to our WhatsApp number or visit our office.",
    "بیرون ملک ڈرائیونگ کے لیے انٹرنیشنل ڈرائیونگ لائسنس کا حصول اور تجدید اب ٹائم سیو سروسز کے پلیٹ فارم پر دستیاب ہے۔": "Getting and renewing an international driving license for driving abroad is now available on the Time Save Services platform.",
    "پاسپورٹ کی کاپی (جس پر ویزا لگا ہو)": "Copy of Passport (with visa stamped)",
    "لوکل ڈرائیونگ لائسنس کی کاپی": "Copy of Local Driving License",
    "ایک عدد پاسپورٹ سائز تصویر": "One Passport Size Photograph",
    "کورٹ فیس کا ٹکٹ (حسبِ ضرورت)": "Court Fee Ticket (if required)",
    "یہ تمام دستاویزات لے کر ہمارے دفتر تشریف لائیں یا ان کی واضح تصاویر ہمارے واٹس ایپ نمبر پر ارسال کریں تاکہ آپ کا کام فوری شروع کیا جا سکے۔": "Bring all these documents to our office or send their clear pictures to our WhatsApp number so that your work can be started immediately.",
    "اب اراضی کے انتقال اور رجسٹری کی کاپی حاصل کرنے کے لیے اراضی ریکارڈ سینٹر کے چکر لگانے کی ضرورت نہیں۔ ٹائم سیو سروسز کے ذریعے گھر بیٹھے یہ سہولت حاصل کریں۔": "Now there is no need to visit the Arazi Record Center to get the land transfer (mutation) and registry copy. Get this facility from home through Time Save Services.",
    "اراضی کا انتقال:": "Land Transfer (Mutation):",
    "جائیداد کی خرید و فروخت یا وراثت کے بعد زمین کا انتقال (Mutation) فوری اور محفوظ طریقے سے۔": "Quick and secure land transfer (mutation) after buying/selling or inheritance of property.",
    "رجسٹری کی کاپی:": "Registry Copy:",
    "گمشدہ یا پرانی رجسٹری کی تصدیق شدہ کاپی (Certified Copy) کا باآسانی حصول۔": "Easy procurement of a certified copy of a lost or old registry.",
    "کمپیوٹرائزڈ ریکارڈ:": "Computerized Record:",
    "پٹواری کے فرسودہ نظام سے نجات، اب آپ کی زمین کا تمام ریکارڈ کمپیوٹرائزڈ اور تصدیق شدہ۔": "Freedom from the outdated Patwari system, now all your land records are computerized and verified.",
    "تفصیلات جاننے اور اپنے اراضی کے معاملات کو قانونی اور شفاف انداز میں حل کرنے کے لیے ہمارے واٹس ایپ نمبر پر رابطہ کریں یا دفتر تشریف لائیں۔": "To know the details and resolve your land matters in a legal and transparent manner, contact our WhatsApp number or visit our office.",
    "اب ریلوے اسٹیشن کی لمبی قطاروں میں لگنے سے بچیں اور ٹائم سیو سروسز کے ذریعے گھر بیٹھے اپنی ٹرین کی ای ٹکٹ حاصل کریں۔": "Now avoid standing in long queues at the railway station and get your train's e-ticket from home through Time Save Services.",
    "آن لائن بکنگ:": "Online Booking:",
    "پاکستان بھر میں کسی بھی شہر کے لیے ٹرین کی سیٹ باآسانی بک کروائیں۔": "Easily book a train seat for any city across Pakistan.",
    "ای ٹکٹ کا حصول:": "Getting E-Ticket:",
    "بکنگ کے فوراً بعد اپنے موبائل پر ای ٹکٹ (SMS یا WhatsApp) کے ذریعے موصول کریں۔": "Receive the e-ticket on your mobile via SMS or WhatsApp immediately after booking.",
    "کلاس کا انتخاب:": "Choosing Class:",
    "اے سی سلیپر، اے سی بزنس، یا اکانومی کلاس، اپنی پسند اور بجٹ کے مطابق سیٹ منتخب کریں۔": "AC Sleeper, AC Business, or Economy Class, choose a seat according to your preference and budget.",
    "سفر کی تاریخ اور روٹ کی تفصیلات کے ساتھ ہمارے واٹس ایپ نمبر پر رابطہ کریں اور گھر بیٹھے اپنی ٹکٹ بک کروائیں۔": "Contact our WhatsApp number with the travel date and route details and book your ticket from home.",
    "پاکستان مرکنٹائل ایکسچینج (PMEX)": "Pakistan Mercantile Exchange (PMEX)",
    "پاکستان اسٹاک ایکسچینج (PSX)": "Pakistan Stock Exchange (PSX)",
    "اکاؤنٹ اوپننگ کے لیے ضروری تفصیلات اور کاغذات:": "Details and documents required for account opening:",
    "پاکستان مرکنٹائل ایکسچینج میں ٹریڈنگ اکاؤنٹ کھولنے کے لیے درج ذیل معلومات اور کاغذات درکار ہوں گے:": "The following information and documents will be required to open a trading account in the Pakistan Mercantile Exchange:",
    "پاکستان اسٹاک ایکسچینج (RDA/Sahulat/Normal Account) میں ٹریڈنگ اکاؤنٹ کھولنے کے لیے درج ذیل معلومات اور کاغذات درکار ہوں گے:": "The following information and documents will be required to open a trading account in the Pakistan Stock Exchange (RDA/Sahulat/Normal Account):",
    "اصلی شناختی کارڈ کی کاپی (فرنٹ اور بیک)": "Original ID card copy (Front and Back)",
    "ایکٹیو ای میل ایڈریس (Active Email Address)": "Active Email Address",
    "ایکٹیو موبائل نمبر (جو آپکے نام پر ہو)": "Active Mobile Number (registered in your name)",
    "بینک اکاؤنٹ کی تفصیل (IBAN نمبر اور چیک بک کی کاپی / اکاؤنٹ مینٹیننس سرٹیفکیٹ)": "Bank Account Details (IBAN Number and Copy of Cheque Book / Account Maintenance Certificate)",
    "آمدنی کا ثبوت (جاب لیٹر یا سیلری سلپ / بزنس لیٹر ہیڈ)": "Proof of Income (Job Letter or Salary Slip / Business Letterhead)",
    "خصوصی آفر!": "Special Offer!",
    "ٹائم سیو سروسز": "Time Save Services",
    "کے توسط سے اکاؤنٹ اوپن کروانے پر": "upon opening an account through",
    "ایک ماہ کی مفت ٹریننگ بھی دے گا۔": "will also provide one month free training.",
    "ٹائم سیو سروسز کے توسط سے اکاؤنٹ اوپن کروانے پر ٹائم سیو سروسز ایک ماہ کی مفت ٹریننگ بھی دے گا۔": "Time Save Services will also provide one month of free training upon opening an account through Time Save Services.",
    "اکاؤنٹ اوپننگ کی کوئی اضافی فیس نہیں لی جائے گی، ہمارا کمیشن صرف فرنٹ اینڈ لوڈ (Front End Load) پر ہوگا۔": "No extra account opening fee will be charged; our commission will only be on the Front End Load."
};

document.addEventListener('DOMContentLoaded', () => {
    const toggleBtn = document.getElementById('lang-toggle-btn');
    if (!toggleBtn) return;

    let isEnglish = false;

    function walkDOM(node, func) {
        func(node);
        node = node.firstChild;
        while (node) {
            walkDOM(node, func);
            node = node.nextSibling;
        }
    }

    function toggleLanguage() {
        isEnglish = !isEnglish;

        // Update document attributes
        document.documentElement.lang = isEnglish ? 'en' : 'ur';
        document.documentElement.dir = isEnglish ? 'ltr' : 'rtl';

        // Update button appearance
        toggleBtn.innerHTML = isEnglish ? '<i class="fa-solid fa-language"></i> اردو / Urdu' : '<i class="fa-solid fa-language"></i> English';
        toggleBtn.style.fontFamily = isEnglish ? "'Noto Nastaliq Urdu', serif" : "'Inter', sans-serif";

        // Translate text nodes
        walkDOM(document.body, node => {
            if (node.nodeType === 3) { // Text node
                let text = node.nodeValue.trim();
                let parentNode = node.parentNode;

                // Avoid translating scripts/styles
                if (parentNode && (parentNode.tagName === 'SCRIPT' || parentNode.tagName === 'STYLE')) return;

                if (text && isEnglish) {
                    let lookupText = text.replace(/\s+/g, ' '); // Normalize spaces
                    if (translations[lookupText]) {
                        node._urduText = node.nodeValue; // Store exact original with format/spaces preserved
                        node.nodeValue = node.nodeValue.replace(text, translations[lookupText]);
                    }
                } else if (!isEnglish) {
                    // Revert back
                    if (node._urduText) {
                        node.nodeValue = node._urduText;
                    }
                }
            } else if (node.nodeType === 1) { // Element node
                if (node.hasAttribute('placeholder')) {
                    let placeholder = node.getAttribute('placeholder').trim();
                    if (isEnglish && translations[placeholder]) {
                        node.setAttribute('data-ur-placeholder', placeholder);
                        node.setAttribute('placeholder', translations[placeholder]);
                    } else if (!isEnglish && node.hasAttribute('data-ur-placeholder')) {
                        node.setAttribute('placeholder', node.getAttribute('data-ur-placeholder'));
                    }
                }
            }
        });
    }

    toggleBtn.addEventListener('click', toggleLanguage);
});
